(()=>{"use strict";const $=id=>document.getElementById(id),c=window.CLIENT_PORTAL_CONFIG||{},ok=c.supabaseUrl&&!c.supabaseUrl.includes("PASTE_")&&c.supabaseAnonKey&&!c.supabaseAnonKey.includes("PASTE_"),sb=ok?supabase.createClient(c.supabaseUrl,c.supabaseAnonKey):null;let rec=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x]));
function contract(x){const d=x.session_date?new Date(x.session_date+"T12:00:00").toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}):"the scheduled date";return `<p>This Photography Agreement is between <strong>Camille Acosta Photography</strong> (“Photographer”) and <strong>${esc(x.client_name)}</strong> (“Client”) for a ${esc(x.session_type||"photography")} session scheduled for <strong>${d}</strong>.</p>
<h2>1. Session & Fee</h2><p>The session fee is <strong>${esc(x.session_fee||"$150")}</strong>. Session timing, location, and included deliverables are those shown in the Client Portal unless otherwise agreed in writing.</p>
<h2>2. Rescheduling & Cancellation</h2><p>Client should provide reasonable notice to reschedule or cancel. Photographer may reschedule for illness, unsafe weather, emergency, or circumstances outside reasonable control. Any deposit, refund, or rescheduling terms separately agreed in writing also apply.</p>
<h2>3. Delivery & Artistic Style</h2><p>Photographer will select and edit the strongest images in her established artistic style. Exact image counts are estimates unless specifically guaranteed in writing.</p>
<h2>4. Copyright & Personal Use</h2><p>Photographer retains copyright. Client receives personal-use rights to download, print, and share delivered images. Commercial resale, substantial alteration, or transfer of copyright is not included unless separately agreed.</p>
<h2>5. Model Release</h2><p>Client grants Photographer permission to use session photographs for portfolio, website, social media, studio samples, advertising, and promotional purposes. Client may request a written privacy exception before the session.</p>
<h2>6. Cooperation, Safety & Liability</h2><p>Client is responsible for timely arrival, cooperation, supervision of minors, and disclosing material safety concerns. Photographer is not responsible for missed images caused by lateness, non-cooperation, venue restrictions, weather, or circumstances outside reasonable control. To the extent permitted by law, Photographer’s liability relating to the session will not exceed amounts paid for the session.</p>
<h2>7. Gallery</h2><p>If a Google Photos or other gallery link is provided, Client is responsible for downloading and backing up desired images. Shared links may later be disabled or replaced.</p>
<h2>8. Referral Discount</h2><p>A Client referral that results in a qualifying new booked photography contract may earn the referring Client <strong>10% off one future photography contract</strong>. The discount is non-cash, non-transferable, applies once per qualifying referral, and cannot be combined with another promotion unless Photographer agrees otherwise.</p>
<h2>9. Entire Agreement</h2><p>This agreement, together with written session-specific terms accepted by both parties, reflects the agreement for the session. Changes should be made in writing.</p><p><em>Beta contract template. Have the final contract reviewed for your business and jurisdiction before relying on it as a production legal document.</em></p>`}
async function show(){if(!sb){$("loginMessage").textContent="Portal beta is not connected yet.";return}const {data:{session}}=await sb.auth.getSession();if(!session){$("loginView").hidden=false;$("portalView").hidden=true;return}const {data}=await sb.from("clients").select("*").eq("user_email",session.user.email).maybeSingle();if(!data){$("loginMessage").textContent="Signed in, but Camille has not activated a portal for this email yet.";return}rec=data;$("loginView").hidden=true;$("portalView").hidden=false;$("contractView").hidden=true;$("clientName").textContent=`Hi, ${(data.client_name||"there").split(" ")[0]}.`;$("sessionType").textContent=data.session_type||"Photography Session";$("sessionDate").textContent=data.session_date?new Date(data.session_date+"T12:00:00").toLocaleDateString():"To be confirmed";$("sessionTime").textContent=data.session_time||"To be confirmed";$("sessionLocation").textContent=data.session_location||"To be confirmed";$("sessionFee").textContent=data.session_fee||"$150";const signed=!!data.contract_signed_at;$("contractHeading").textContent=signed?"Agreement signed":"Agreement pending";$("contractSummary").textContent=signed?`Signed ${new Date(data.contract_signed_at).toLocaleString()}`:"Review and sign your agreement before the session.";$("openContractButton").textContent=signed?"VIEW AGREEMENT":"REVIEW CONTRACT";if(data.gallery_url){$("galleryButton").href=data.gallery_url;$("galleryButton").classList.remove("disabled");$("galleryMessage").textContent="Your gallery is ready."}}
$("magicLinkForm").addEventListener("submit",async e=>{e.preventDefault();if(!sb)return show();$("loginMessage").textContent="Sending…";const {error}=await sb.auth.signInWithOtp({email:$("clientEmail").value.trim(),options:{emailRedirectTo:`${location.origin}/client.html`}});$("loginMessage").textContent=error?error.message:"Check your email for your secure sign-in link."});
$("signOutButton").addEventListener("click",async()=>{await sb?.auth.signOut();location.reload()});$("openContractButton").addEventListener("click",()=>{if(!rec)return;$("portalView").hidden=true;$("contractView").hidden=false;$("contractText").innerHTML=contract(rec);if(rec.contract_signed_at)$("signatureArea").innerHTML=`<p><strong>Signed by:</strong> ${esc(rec.contract_signed_name||rec.client_name)}</p><p><strong>Signed:</strong> ${new Date(rec.contract_signed_at).toLocaleString()}</p>`});$("backToPortal").addEventListener("click",()=>{$("contractView").hidden=true;$("portalView").hidden=false});$("signContractButton").addEventListener("click",async()=>{const name=$("signatureName").value.trim();if(!$("contractConsent").checked||!name){$("contractMessage").textContent="Check the agreement box and type your legal name.";return}const {error}=await sb.from("clients").update({contract_signed_name:name,contract_signed_at:new Date().toISOString(),contract_version:"beta-1"}).eq("id",rec.id);$("contractMessage").textContent=error?error.message:"Agreement signed.";if(!error)setTimeout(show,600)});sb?.auth.onAuthStateChange(()=>setTimeout(show,0));show()})();